name: cookbook-dev
channels:
  - conda-forge
dependencies:
  - jupyterlab
  - mystmd
  - jupyterlab-myst
  - xarray
  - pandas
  - dask
  - tensorflow
  - matplotlib
  - cartopy
  - netCDF4
  - scipy
  - h5netcdf
  - pip
  - pip:
      - global-land-mask
    